exports = async function onNewCustomFunctionUser({ user }) {
  try{
    // This is the user's internal account ID that was generated by your app
  const internalId = user.id;
  console.log(internalId);
  // This is the external ID returned from the authentication function
  const customFunctionIdentity = user.identities.find((id) => {
    return id.provider_type === "custom-function";
  });
  const externalId = customFunctionIdentity.id;
  console.log(externalId);
  // Create a custom user data document for the user
  const mdb = context.services.get("mongodb-atlas");
  const users = mdb.db("GoGetKids").collection("customUserData");
  return await users.insertOne({
    // Include both the internal ID and external ID
    user_id: internalId,
    external_id: externalId,
  });
  }catch(error){
    console.error("error")
  }
};